services:
  # Frontend Service
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    plan: free # or another plan depending on your needs
    routes:
      - src: /frontend/*
        dest: /frontend/

  # Backend Service
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    plan: free # or another plan depending on your needs
    routes:
      - src: /backend/*
        dest: /backend/

  # Login Service
  - type: web
    name: login
    env: node
    buildCommand: cd login && npm install && npm run build
    startCommand: cd login && npm start
    plan: free # or another plan depending on your needs
    routes:
      - src: /login/*
        dest: /login/
