services:
  - type: web
    name: matinee-web-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    autoDeploy: true

workers:
  - type: worker
    name: matinee-worker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
